[[DeviceList]]
  Name = "Random-Float-Device"
  ProfileName = "Random-Float-Device"
  Description = "Example of Device Virtual"
  Labels = [ "device-virtual-example" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "device-virtual-float-01"
      Protocol = "300"
  [[DeviceList.AutoEvents]]
    Interval = "30s"
    OnChange = false
    SourceName = "Float32"
  [[DeviceList.AutoEvents]]
    Interval = "30s"
    OnChange = false
    SourceName = "Float64"
