name: edgex-config-provider
base: core20

version: example
summary: Example EdgeX snaps config provider
description: |
  This is an example snap to provide configuration files to EdgeX service snaps.

grade: stable
confinement: strict

# The consumer plugs can connect to these slots.
# Each source path get mounted as a read-only directory
#   inside the corresponding plug's target path.
slots:
  app-service-configurable:
    interface: content
    source:
      read: 
        - $SNAP/app-service-configurable/res/http-export
        - $SNAP/app-service-configurable/res/mqtt-export
  device-mqtt:
    interface: content
    source:
      read: 
        - $SNAP/device-mqtt/res

# Prepare the config files for slots
parts:
  app-service-configurable:
    # This example takes source files from the local file system
    plugin: dump
    source: examples/app-service-configurable
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/app-service-configurable

      mkdir -p $TARGET
      cp -vr res $TARGET/res
  device-mqtt:
    # This example takes source files from the local file system
    plugin: dump
    source: examples/device-mqtt
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/device-mqtt

      mkdir -p $TARGET
      cp -vr res $TARGET/res
